<?php
// This file generated by Propel 1.7.2 convert-conf target
return array (
  'Author' => 'models/Author.php',
  'AuthorPeer' => 'models/AuthorPeer.php',
  'AuthorQuery' => 'models/AuthorQuery.php',
  'AuthorTableMap' => 'models/map/AuthorTableMap.php',
  'BaseAuthor' => 'models/om/BaseAuthor.php',
  'BaseAuthorPeer' => 'models/om/BaseAuthorPeer.php',
  'BaseAuthorQuery' => 'models/om/BaseAuthorQuery.php',
  'BaseBook' => 'models/om/BaseBook.php',
  'BaseBookPeer' => 'models/om/BaseBookPeer.php',
  'BaseBookQuery' => 'models/om/BaseBookQuery.php',
  'Book' => 'models/Book.php',
  'BookPeer' => 'models/BookPeer.php',
  'BookQuery' => 'models/BookQuery.php',
  'BookTableMap' => 'models/map/BookTableMap.php',
);