<?php
// This file generated by Propel 1.7.2 convert-conf target
// from XML runtime conf file /app/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'disable-instance-pooling-problem' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=10.11.12.14;port=3306;dbname=database;charset=utf8',
        'user' => 'user',
        'password' => 'password',
      ),
    ),
    'default' => 'disable-instance-pooling-problem',
  ),
  'generator_version' => '1.7.2',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-disable-instance-pooling-problem-conf.php');
return $conf;